### ISSUE TITLE
Add an entry for dynamic changes to CSS appearance not appearing to work

### ISSUE THREAD

**Issue by wisniewskit** [webcompat/knowledge-base#122]
Due to a bug being fixed in [bz1786521](https://bugzilla.mozilla.org/show_bug.cgi?id=1786521), attempts to change `style.appearance` or `style["-moz-appearance"]` on input fields appears to do nothing in Firefox.

This can cause, for instance, number input's spinner buttons to still be visible on websites when they should not be, leading to reports such as:
- https://github.com/webcompat/web-bugs/issues/107783
- https://github.com/webcompat/web-bugs/issues/109468
-

**Comment by jgraham** [comment]
I don't think there's much value adding this given it's already fixed (and we just requested an uplift). Feel free to reopen if you disagree.
