### ISSUE TITLE
Update svg-without-definite-size.yml entry

### ISSUE THREAD

**Issue by janodvarko** [webcompat/knowledge-base#176]
The platform issue for the following entry has been fixed:
https://github.com/webcompat/knowledge-base/blob/main/data/svg-without-definite-size.yml

[Bug 1521882](https://bugzilla.mozilla.org/show_bug.cgi?id=1521882) - SVG without width/height specified has different intrinsic-sizing behavior in Chrome vs Firefox (e.g. in a float or in flexbox)
* Closed as a dup of [bug 1340715](https://bugzilla.mozilla.org/show_bug.cgi?id=1340715)
* WPT PR [created](https://github.com/web-platform-tests/wpt/pull/35755) merged and synced upstream

**Comment by ksy36** [comment]
I've just merged a PR that moves this file to to https://github.com/webcompat/knowledge-base/tree/main/data/resolved/106.0.0
