### ISSUE TITLE
Add entry about popup-blocking causing confusing UX

### ISSUE THREAD

**Issue by denschub** [webcompat/knowledge-base#76]
Examples:

- https://github.com/webcompat/web-bugs/issues/107903
- https://bugzilla.mozilla.org/show_bug.cgi?id=1739655

**Comment by ksy36** [comment]
One more related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1699799 (Clicking the "Print" button in Gmail triggers the popup blocker but works in Chrome)
